### PR TITLE
Get tests passing

### PR DESCRIPTION
**Pull request by adam-beck**

### CODE REVIEW

**Comment by kylefarris** [comment]
Hell yeah! Thanks man!

**Comment by adam-beck** [comment]
This will probably break for you locally if it was working before. I was focusing on the CI more. 

Also, will you be able to publish a new npm package soon?

**Comment by kylefarris** [comment]
Yeah, it definitely breaks local tests since I'm running on a CentOS box but that's fine... I know what to change on my end to make the tests pass locally. I'm going to be releasing a v1.0.1 momentarily.

**Comment by adam-beck** [comment]
Awesome! Thank you

**Comment by kylefarris** [comment]
Scratch that... it'll be v1.0.2 because I'm a dumb ass and published version 1.0.1 from the branch for 1.0.0 instead of Master... 🤦

**Pull request merged**
