### PR TITLE
Fix the problem reported in #102

### PR DESCRIPTION
**Pull request by benzino77**
Proper error handling in scanStream method.

### CODE REVIEW

**Comment by benzino77** [comment]
hmmm... that is strange. On my side all tests are passing without errors...

**Comment by kylefarris** [comment]
Sometimes I have to run the CI tests a few times to get them to pass. Just something weird with the environment it runs in, I think.

**Comment by benzino77** [comment]
There is a problem with node version, I think. On my side (on my workstation) tests run on node `v17` sometimes failing:
```sh
Now using node v17.9.1 (npm v8.11.0)
❯ npm run test

> clamscan@2.1.2 test
> make test

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: eslint-config-airbnb@15.1.0
npm ERR! Found: eslint@7.25.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.25.0" from the root project
npm ERR!   peer eslint@">= 4.12.1" from babel-eslint@10.1.0
npm ERR!   node_modules/babel-eslint
npm ERR!     dev babel-eslint@"^10.1.0" from the root project
npm ERR!   5 more (eslint-config-prettier, eslint-plugin-chai-friendly, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^3.19.0 || ^4.3.0" from eslint-config-airbnb@15.1.0
npm ERR! node_modules/eslint-config-airbnb
npm ERR!   dev eslint-config-airbnb@"^15.0.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: eslint@4.19.1
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^3.19.0 || ^4.3.0" from eslint-config-airbnb@15.1.0
npm ERR!   node_modules/eslint-config-airbnb
npm ERR!     dev eslint-config-airbnb@"^15.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/benzino/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/benzino/.npm/_logs/2022-08-11T08_57_29_795Z-debug-0.log
make: *** [Makefile:5: all] Error 1
```

on all other node versions (v12, v13, v14, v15, v16) I'm not observing such behavior.

**Comment by benzino77** [comment]
Kyle are you want me to do something more with this?

**Comment by carboneater** [comment]
@benzino77 the error you pasted is related to npm 8, where it now enforces peer dependencies strictly

**Comment by benzino77** [comment]
> > @benzino77 the error you pasted is related to npm 8, where it now enforces peer dependencies strictly
> 
> Good news is I gnawed at this problem over the last few days. It's solved in #106

That is great! So if your PR will be merged then there is a chance that this one will not fail on tests.

**Comment by benzino77** [comment]
@kylefarris since #106 was merged could you please rerun tests for this PR? I have no idea how should I do it on my own....

**Comment by origooo** [comment]
Not sure what the status of this PR is, but it seems to fix the issues with error handling for me. Without this fix, sometimes the EPIPE error is not catchable which breaks my api endpoints somewhat. With the fix it is indeed properly caught.

Anything I can do to help?

**Comment by kylefarris** [comment]
Hey guys, I'll take a look at this today and run the tests and get it merged in if all is well. Sorry for the delay! Been really busy with work :)

**Comment by origooo** [comment]
Some more information. I've added a test case which passes a too large stream through scanStream (which was my initial problem). The fix suggested in this PR helps in catching the two types of errors which can occur from that. The errors are either EPIPE or NodeClamError "INSTREAM size limit exceeded".

What I don't understand is that the type of error I end up catching is inconsistent. This is okay since I can look for both types of errors. But do we know where the inconsistency comes from? It would be sweet if we could look for e.g. a "SIZE_LIMIT_EXCEEDED" or so but that would not be possible without fixing the inconsistency. I have seen that you've mentioned in other issue threads that we can look for NodeClamError + `data.error.includes("INSTREAM size limit exceeded")`. That might be better instead of adding specific error handling for all potential ClamAV errors.

I know very little about streams in general, but could it be that the stream sometimes is closed/ended earlier in some cases?

**Test results**
INSTREAM is printed, EPIPE is logged after test result is printed.
```
  scanStream
NodeClamError: An error occurred while scanning the piped-through stream: INSTREAM size limit exceeded.
    at NodeClam._processResult (/Users/patrikbackstrom/Git/loopme/tmp/clamscan/index.js:797:20)
    ...
}
    ✔ should exceed max file size **<--- TEST RESULT**
node-clam: Error emitted from ClamAV socket:  Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

  1 passing (21ms)
```
INSTREAM is **NOT** printed. EPIPE is logged before the test result is printed.
```
  scanStream
node-clam: Error emitted from ClamAV socket:  Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
    ✔ should exceed max file size **<--- TEST RESULT**

  1 passing (23ms)
```

**Comment by kylefarris** [comment]
Merged! Thanks everyone! I'm going to get dependencies updated and a new version published shortly.

**Pull request merged**
